spring:
  application:
    name: manage
  profiles:
    active: dev

server:
  port: 8080
logging:
  level:
    root: info
    com.sxm.blog: info
    org.springframework.boot.autoconfigure: error
  file:
    name: log/blog.log

mybatis:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  type-aliases-package: com.sxm.blog.admin.entity